services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # 開発環境用設定
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    networks:
      - app-network
    # ヘルスチェックを使用せず、起動時間を短くする
    restart: on-failure:3

  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/one-account-realm
      - KEYCLOAK_CLIENT_ID=web-client
      - KEYCLOAK_CLIENT_SECRET=your-secret-key
    depends_on:
      - keycloak
    networks:
      - app-network
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-app/.env.local
    depends_on:
      - backend-api
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data:
