services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export-fixed.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    networks:
      - app-network
    # ヘルスチェックを使用せず、起動時間を短くする
    restart: on-failure:3

  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/one-account-realm
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - keycloak
    networks:
      - app-network

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:a-secure-random-string-for-development-only}
      - KEYCLOAK_CLIENT_ID=gmo-coin-client
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:your-client-secret-here}
      - KEYCLOAK_ISSUER=http://localhost:8080/realms/one-account-realm
      - BACKEND_API_URL=http://backend-api:8080
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data:
