server:
  port: 8080

spring:
  application:
    name: gmo-coin-sample
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gmo-coin-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret-here}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/one-account-realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/one-account-realm}

logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.security.oauth2]": DEBUG

# カスタムCORS設定（SecurityConfigで使用）
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
